version: '3.7'

services: 
  minio:
    restart: always 
    image: minio/minio:RELEASE.2023-03-24T21-41-23Z
    ports:
      - "9000:9000"
      - "9001:9001" 
    networks:
      - mlflow_net 
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - minio_data:/data 
    command: server /data --console-address ':9001' --address ':9000'

  db:
    restart: always 
    image: mysql:8.0.32 
    ports:
      - "3306:33606" 
    networks:
      - mlflow_net 
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes: 
      - db_data:/var/lib/mysql 

  mlflow:
    restart: always
    build: ./mlflow
    image: mlflow
    depends_on:
      - db
      - minio
    ports:
      - "5050:5000"
    networks:
      - mlflow_net
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow/ --host 0.0.0.0

networks:
  mlflow_net:

volumes: 
  db_data:
  minio_data: